{
  "WorkItem": {
    "AffectedComponent": {
      "Name": "",
      "DisplayName": ""
    },
    "ClosedComment": "",
    "ClosedDate": null,
    "CommentCount": 0,
    "Custom": null,
    "Description": "$cell2->getCalculatedValue() not happy with 3d reference\n \nExcel file attached.\nReading code below.\nError here: (in the 176 path, I've replaced Calculation.php and Cell.php with latest versions, from svn / trunk)\n \n> php bug_3d.php\n> php bug_3d.php\n03:15:56 Load 3d bug file\nPHP Fatal error:  Uncaught exception 'Exception' with message '2.4d!B8 -> 2.4d!C6 -> internal error' in C:\\Documents and Settings\\Brent\\My Documents\\data\\projects\\Chexel 10\\PHPExcel176\\Classes\\PHPExcel\\Cell.php:288\nStack trace:\n#0 C:\\Documents and Settings\\Brent\\My Documents\\data\\projects\\Chexel 10\\PHPExcel176\\Tests\\bug_3d.php(18): PHPExcel_Cell->getCalculatedValue()\n#1 {main}\n  thrown in C:\\Documents and Settings\\Brent\\My Documents\\data\\projects\\Chexel 10\n\\PHPExcel176\\Classes\\PHPExcel\\Cell.php on line 288\n \n \n>\nCode:\n<?php\n/**\n * illustrate 3d reference bug in worksheet 2.4d cell B8\n * cell 2.4d!B8 refers to cell C6 which contains a 3d reference to Worksheet 2.4c\n */\n \nerror_reporting(E_ALL);\ndate_default_timezone_set('Europe/London');\nrequire_once '../Classes/PHPExcel/IOFactory.php';\n$ff = \"bug_3d.xls\";\nif (!file_exists($ff)) {exit(\"Oops - we need $ff file to illustrate the bug.\\n\"); }\n \necho date('H:i:s') . \" Load 3d bug file\\n\";\n$objPHPExcel = PHPExcel_IOFactory::load(\"$ff\");\n \n$wks2 = $objPHPExcel->getSheetByName('2.4d');\n$cell2 = $wks2->getCell('B8');\n$v2 = $cell2->getCalculatedValue();\n \necho date('H:i:s') . \" Done with 3d bug.\\r\\n\";\n?>",
    "LastUpdatedDate": "2013-02-21T19:02:14.273-08:00",
    "PlannedForRelease": "",
    "ReleaseVisibleToPublic": false,
    "Priority": {
      "Name": "Low",
      "Severity": 50,
      "Id": 1
    },
    "ProjectName": "PHPExcel",
    "ReportedDate": "2011-09-22T19:18:14.083-07:00",
    "Status": {
      "Name": "Proposed",
      "Id": 1
    },
    "ReasonClosed": {
      "Name": "Unassigned"
    },
    "Summary": "3d reference bug: internal error",
    "Type": {
      "Name": "Issue",
      "Id": 3
    },
    "VoteCount": 1,
    "Id": 16614
  },
  "FileAttachments": [
    {
      "FileId": 5896,
      "FileName": "student_bug_3d.xls",
      "DownloadUrl": ".\\5896"
    }
  ],
  "Comments": []
}